add_newline = true

[character]
success_symbol = "[=>](bold green)" 

[package]
disabled = true

[nodejs]
format = "via [ğŸ¤– $version](bold green) "

[git_commit]
only_detached = false
commit_hash_length = 7
tag_disabled = false

